
title: SN ABOITIZ

description: > # this means to ignore newlines until "baseurl:"
  SN Power is a hydropower development company, operating exclusively in emerging markets. The company is a joint venture between Statkraft and Norfund and has projects and operations in Asia, Latin America and Africa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
highlight: rouge

collections:
  posts:
    permalink: /news/:path/

jekyll_timeago:
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: 'in'
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'

sass:
  style: compressed

gems: [jekyll-timeago]

navbar-menu:
  - title: "About Us"
    slugID: "/about-us/"

  - title: "Our Services"
    slugID: "/our-service/"

  - title: "Csr & Sustainability"
    slugID: "/csr-sustainability/"

  - title: "News"
    slugID: "/news/"

  - title: "FAQs"
    slugID: "/faq/"

  - title: "Careers"
    slugID: "/careers/"

  - title: "Contact Us"
    slugID: "/contact/"


prose:
  rooturl: ""
  siteurl: "https://snaboitiz.github.io/"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: true

      - name: "title"
        field:
          element: "text"
          label: "title"

