
title: SN ABOITIZ
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
highlight: rouge

paginate: 3
paginate_path: "newsroom/page:num/"

collections:
  posts:
    permalink: /newsroom/:path/

jekyll_timeago:
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: 'in'
  prefix_future: ''
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'

sass:
  style: compressed

gems: [jekyll-paginate,jekyll-timeago]

navbar-menu:
  - title: "About Us"
    slugID: "/about-us/"

  - title: "Our Businesses"
    slugID: "/our-business/"

  - title: "Csr & Sustainability"
    slugID: "/csr-sustainability/"

  - title: "Newsroom"
    slugID: "/newsroom/"

  - title: "Careers"
    slugID: "/careers/"

  - title: "Contact"
    slugID: "/contact/"

company:
  - link:
    image: "logo-1.png"

  - link:
    image: "logo-2.png"

  - link:
    image: "logo-3.png"